from io import BytesIO
import json
from zipfile import ZIP_DEFLATED, ZipFile


def compose_html_document(project):
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{project.title}</title>
  <style>
{project.css}
  </style>
</head>
<body>
{project.html}
  <script>
{project.javascript}
  </script>
</body>
</html>
"""


def build_zip(project):
    memory_file = BytesIO()
    with ZipFile(memory_file, "w", ZIP_DEFLATED) as archive:
        archive.writestr("index.html", compose_html_document(project))
        archive.writestr("styles.css", project.css)
        archive.writestr("script.js", project.javascript)
        archive.writestr(
            "README.md",
            f"# {project.title}\n\nGenerated by AI Website Builder.\n\nOpen `index.html` in a browser to preview the site.\n",
        )
    memory_file.seek(0)
    return memory_file


def build_react_project_zip(project):
    memory_file = BytesIO()
    with ZipFile(memory_file, "w", ZIP_DEFLATED) as archive:
        archive.writestr("package.json", '{"scripts":{"dev":"vite","build":"vite build"},"dependencies":{"@vitejs/plugin-react":"latest","vite":"latest","react":"latest","react-dom":"latest"},"devDependencies":{}}')
        archive.writestr("index.html", '<div id="root"></div><script type="module" src="/src/main.jsx"></script>')
        archive.writestr(
            "src/main.jsx",
            'import React from "react";import{createRoot}from"react-dom/client";import"./style.css";const html='
            + json.dumps(project.html)
            + ';function App(){return <div dangerouslySetInnerHTML={{__html: html}}/>}createRoot(document.getElementById("root")).render(<App/>);',
        )
        archive.writestr("src/style.css", project.css)
    memory_file.seek(0)
    return memory_file
